import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Reverts the four id-related migrations:
 *  - AddPatientIdNumber
 *  - BackfillPatientIdNumber
 *  - PatientIdAsNumber
 *  - UserIdAsString
 *  - AlignUserIdsWithPatientIds
 *
 * Returns users.id and patients.id (and every FK column that points at
 * them) to uuid. Existing rows get fresh uuid_generate_v4() values; the
 * mapping is preserved so all relations stay consistent.
 */
export class RevertIdsToUuid1782600000000 implements MigrationInterface {
  name = 'RevertIdsToUuid1782600000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // 1. Drop FKs that depend on users.id / patients.id
    await queryRunner.query(
      `ALTER TABLE "caregivers" DROP CONSTRAINT "FK_655a3051fc7e8ba600f9edf1f3e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "patients" DROP CONSTRAINT "FK_7fe1518dc780fd777669b5cb7a0"`,
    );
    await queryRunner.query(
      `ALTER TABLE "medical_documents" DROP CONSTRAINT "FK_94c6090bd7be7dc6f9aa7d2cf4b"`,
    );
    await queryRunner.query(
      `ALTER TABLE "slots" DROP CONSTRAINT "FK_d2f106327cf1bd5bd82cc5d2ccf"`,
    );
    await queryRunner.query(
      `ALTER TABLE "medical_documents" DROP CONSTRAINT "FK_d31157c1680919456aca9e48170"`,
    );
    await queryRunner.query(
      `ALTER TABLE "visits" DROP CONSTRAINT "FK_5054db93135a6d966fd3939caa6"`,
    );

    // 2. Drop the unique constraints on user_id (they'll be re-created)
    await queryRunner.query(
      `ALTER TABLE "patients" DROP CONSTRAINT IF EXISTS "UQ_7fe1518dc780fd777669b5cb7a0"`,
    );
    await queryRunner.query(
      `ALTER TABLE "patients" DROP CONSTRAINT IF EXISTS "REL_7fe1518dc780fd777669b5cb7a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "caregivers" DROP CONSTRAINT IF EXISTS "UQ_655a3051fc7e8ba600f9edf1f3e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "caregivers" DROP CONSTRAINT IF EXISTS "REL_655a3051fc7e8ba600f9edf1f3"`,
    );

    // 3. Add new uuid PK columns (autogenerated) on users + patients
    await queryRunner.query(
      `ALTER TABLE "users" ADD COLUMN "new_id" uuid NOT NULL DEFAULT uuid_generate_v4()`,
    );
    await queryRunner.query(
      `ALTER TABLE "patients" ADD COLUMN "new_id" uuid NOT NULL DEFAULT uuid_generate_v4()`,
    );

    // 4. Add new uuid FK columns on dependent tables
    await queryRunner.query(
      `ALTER TABLE "patients" ADD COLUMN "new_user_id" uuid`,
    );
    await queryRunner.query(
      `ALTER TABLE "caregivers" ADD COLUMN "new_user_id" uuid`,
    );
    await queryRunner.query(
      `ALTER TABLE "medical_documents" ADD COLUMN "new_uploaded_by_user_id" uuid`,
    );
    await queryRunner.query(
      `ALTER TABLE "slots" ADD COLUMN "new_patient_id" uuid`,
    );
    await queryRunner.query(
      `ALTER TABLE "medical_documents" ADD COLUMN "new_patient_id" uuid`,
    );
    await queryRunner.query(
      `ALTER TABLE "visits" ADD COLUMN "new_patient_id" uuid`,
    );

    // 5. Repoint FK columns via the existing varchar mapping
    await queryRunner.query(
      `UPDATE "patients" p SET "new_user_id" = u."new_id" FROM "users" u WHERE p."user_id" = u."id"`,
    );
    await queryRunner.query(
      `UPDATE "caregivers" c SET "new_user_id" = u."new_id" FROM "users" u WHERE c."user_id" = u."id"`,
    );
    await queryRunner.query(
      `UPDATE "medical_documents" m SET "new_uploaded_by_user_id" = u."new_id" FROM "users" u WHERE m."uploaded_by_user_id" = u."id"`,
    );
    await queryRunner.query(
      `UPDATE "slots" s SET "new_patient_id" = p."new_id" FROM "patients" p WHERE s."patient_id" = p."id"`,
    );
    await queryRunner.query(
      `UPDATE "medical_documents" m SET "new_patient_id" = p."new_id" FROM "patients" p WHERE m."patient_id" = p."id"`,
    );
    await queryRunner.query(
      `UPDATE "visits" v SET "new_patient_id" = p."new_id" FROM "patients" p WHERE v."patient_id" = p."id"`,
    );

    // 6. Drop old PK constraints + old varchar columns
    await queryRunner.query(
      `ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`,
    );
    await queryRunner.query(
      `ALTER TABLE "patients" DROP CONSTRAINT "PK_a7f0b9fcbb3469d5ec0b0aceaa7"`,
    );
    await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "id"`);
    await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "user_id"`);
    await queryRunner.query(`ALTER TABLE "caregivers" DROP COLUMN "user_id"`);
    await queryRunner.query(
      `ALTER TABLE "medical_documents" DROP COLUMN "uploaded_by_user_id"`,
    );
    await queryRunner.query(`ALTER TABLE "slots" DROP COLUMN "patient_id"`);
    await queryRunner.query(
      `ALTER TABLE "medical_documents" DROP COLUMN "patient_id"`,
    );
    await queryRunner.query(`ALTER TABLE "visits" DROP COLUMN "patient_id"`);

    // 7. Rename new columns to canonical names
    await queryRunner.query(
      `ALTER TABLE "users" RENAME COLUMN "new_id" TO "id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "patients" RENAME COLUMN "new_id" TO "id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "patients" RENAME COLUMN "new_user_id" TO "user_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "caregivers" RENAME COLUMN "new_user_id" TO "user_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "medical_documents" RENAME COLUMN "new_uploaded_by_user_id" TO "uploaded_by_user_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "slots" RENAME COLUMN "new_patient_id" TO "patient_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "medical_documents" RENAME COLUMN "new_patient_id" TO "patient_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "visits" RENAME COLUMN "new_patient_id" TO "patient_id"`,
    );

    // 8. Restore NOT NULL on FK columns
    await queryRunner.query(
      `ALTER TABLE "patients" ALTER COLUMN "user_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "caregivers" ALTER COLUMN "user_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "medical_documents" ALTER COLUMN "uploaded_by_user_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "slots" ALTER COLUMN "patient_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "medical_documents" ALTER COLUMN "patient_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "visits" ALTER COLUMN "patient_id" SET NOT NULL`,
    );

    // 9. Restore PK constraints (original names)
    await queryRunner.query(
      `ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`,
    );
    await queryRunner.query(
      `ALTER TABLE "patients" ADD CONSTRAINT "PK_a7f0b9fcbb3469d5ec0b0aceaa7" PRIMARY KEY ("id")`,
    );

    // 10. Restore unique constraints on user_id
    await queryRunner.query(
      `ALTER TABLE "patients" ADD CONSTRAINT "UQ_7fe1518dc780fd777669b5cb7a0" UNIQUE ("user_id")`,
    );
    await queryRunner.query(
      `ALTER TABLE "patients" ADD CONSTRAINT "REL_7fe1518dc780fd777669b5cb7a" UNIQUE ("user_id")`,
    );
    await queryRunner.query(
      `ALTER TABLE "caregivers" ADD CONSTRAINT "UQ_655a3051fc7e8ba600f9edf1f3e" UNIQUE ("user_id")`,
    );
    await queryRunner.query(
      `ALTER TABLE "caregivers" ADD CONSTRAINT "REL_655a3051fc7e8ba600f9edf1f3" UNIQUE ("user_id")`,
    );

    // 11. Restore FK constraints (original names + on-delete actions)
    await queryRunner.query(
      `ALTER TABLE "caregivers" ADD CONSTRAINT "FK_655a3051fc7e8ba600f9edf1f3e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "patients" ADD CONSTRAINT "FK_7fe1518dc780fd777669b5cb7a0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "medical_documents" ADD CONSTRAINT "FK_94c6090bd7be7dc6f9aa7d2cf4b" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "slots" ADD CONSTRAINT "FK_d2f106327cf1bd5bd82cc5d2ccf" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "medical_documents" ADD CONSTRAINT "FK_d31157c1680919456aca9e48170" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "visits" ADD CONSTRAINT "FK_5054db93135a6d966fd3939caa6" FOREIGN KEY ("patient_id") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {
    throw new Error(
      'RevertIdsToUuid is the explicit revert. It cannot be auto-reverted.',
    );
  }
}
